language: python
python:
  - "3.7"
  - "3.7-dev"
env:
  - DJANGO=2.2.5 DB=sqlite3
before_install:
  - export DJANGO_SETTINGS_MODULE=oms_cms.config.test_settings
install:
  - git clone --depth=50 --branch=develop https://github.com/DJWOMS/oms_cms.git .
  - pip install -r req.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
