language: python
python:
  - "3.7"
  - "3.7-dev"
env:
  - DJANGO=2.2.5 DB=sqlite3
before_install:
  - export DJANGO_SETTINGS_MODULE=ledenbestand.settings.local
install:
  - pip install -r req.txt
#before_script:
#  python manage.py
script:
 - python oms_cms/manage.py test
