# Generated by Django 2.2.4 on 2019-08-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('icon_ui', models.CharField(blank=True, default='', max_length=500, verbose_name='Класс иконки')),
                ('icon', models.FileField(blank=True, null=True, upload_to='soc_icon/', verbose_name='Иконка')),
                ('link', models.URLField(verbose_name='URL Соц. сети')),
            ],
            options={
                'verbose_name': 'Соц. сеть',
                'verbose_name_plural': 'Соц. сети',
            },
        ),
    ]
