# Generated by Django 2.2.5 on 2019-11-25 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(related_name='users_like', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
