# Generated by Django 2.2.5 on 2019-12-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191125_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=7, verbose_name='Язык')),
                ('title', models.CharField(help_text='Имя которое отображается на сайте', max_length=100, verbose_name='Название')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('icon', models.ImageField(upload_to='filters/', verbose_name='Изображение')),
                ('icon_ui', models.CharField(help_text='Иконка из вашего UI', max_length=50, verbose_name='Иконка')),
                ('published', models.BooleanField(default=True, verbose_name='Отображать?')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='filters',
            field=models.ManyToManyField(blank=True, to='news.FilterPost', verbose_name='Фильтр'),
        ),
    ]
