# Generated by Django 2.2.5 on 2019-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpost',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='filters/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='filterpost',
            name='icon_ui',
            field=models.CharField(blank=True, help_text='Иконка из вашего UI', max_length=50, null=True, verbose_name='Иконка'),
        ),
    ]
