# Generated by Django 2.2.5 on 2019-12-09 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191207_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpost',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='filters/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='users_like', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
