# Generated by Django 2.2.4 on 2019-08-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя поисковой системы', max_length=60, verbose_name='Имя')),
                ('key', models.CharField(max_length=150, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Подключение ПС',
                'verbose_name_plural': 'Подключение ПС',
            },
        ),
        migrations.CreateModel(
            name='CounterForSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя счетчика', max_length=60, verbose_name='Имя')),
                ('code', models.TextField(help_text='Код счетчика или метрики', verbose_name='Код')),
                ('published', models.BooleanField(default=True, verbose_name='Включен')),
            ],
            options={
                'verbose_name': 'Счетчики и аналитика для сайта',
                'verbose_name_plural': 'Счетчики и аналитика для сайта',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=60, verbose_name='Title')),
                ('description_page', models.CharField(max_length=150, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'SEO модуль',
                'verbose_name_plural': 'SEO модуль',
            },
        ),
    ]
