# Generated by Django 2.2.5 on 2019-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='block_page/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.CharField(blank=True, help_text='Укажите url', max_length=500, null=True, verbose_name='url'),
        ),
    ]
