# Generated by Django 2.2.5 on 2019-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191016_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подзаголовок'),
        ),
    ]
