# Generated by Django 2.2.5 on 2019-12-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191115_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms_gallery.Photo', verbose_name='Изображение'),
        ),
    ]
