# Generated by Django 2.1.7 on 2019-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpySearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(max_length=1000, verbose_name='Запрос')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'Запрос поиска',
                'verbose_name_plural': 'Запросы поиска',
            },
        ),
    ]
