# Generated by Django 2.2.5 on 2019-09-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms_gallery', '0002_auto_20190714_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=7, verbose_name='Язык')),
                ('slug', models.SlugField(blank=True, help_text='Укажите url', max_length=500, null=True, verbose_name='url')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Под заголовок')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oms_gallery.Gallery', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Инфо блок',
                'verbose_name_plural': 'Инфо блок',
            },
        ),
    ]
