# Generated by Django 2.2.5 on 2019-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, help_text='Укажите url', max_length=500, null=True, verbose_name='url'),
        ),
    ]
